name: hirall_mobile_companion
description: "Hirall POS - Mobile Companion, Wireless Barcode Gun, Floor Stock In & Cashier App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  lucide_icons_flutter: ^3.1.17
  shared_preferences: ^2.2.3
  http: ^1.2.1
  intl: ^0.19.0
  barcode_widget: ^2.0.4
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
