use axum::{
    extract::{Path, Query, State},
    routing::get,
    Json, Router,
};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::types::BigDecimal;
use uuid::Uuid;

use crate::app::state::AppState;
use crate::core::auth::MaybeAuthUser;
use crate::core::errors::{AppError, AppResult};

#[derive(Debug, Deserialize)]
pub struct CreateSaleItemRequest {
    pub product_id: Uuid,
    pub product_name: String,
    pub sku: String,
    pub quantity: BigDecimal,
    pub unit_price: BigDecimal,
    pub tax_rate: Option<BigDecimal>,
    pub tax_amount: Option<BigDecimal>,
    pub discount_amount: Option<BigDecimal>,
    pub total_amount: BigDecimal,
}

#[derive(Debug, Deserialize)]
pub struct CreateSalePaymentRequest {
    pub payment_method: String, // CASH, CARD, MOBILE_MONEY
    pub amount: BigDecimal,
    pub currency: Option<String>,
    pub reference: Option<String>,
    pub change_given: Option<BigDecimal>,
}

#[derive(Debug, Deserialize)]
pub struct CreateSaleRequest {
    pub client_sale_id: Uuid, // ID generated by desktop SQLite
    pub branch_id: Uuid,
    pub pos_terminal_id: Option<Uuid>,
    #[allow(dead_code)]
    pub cashier_session_id: Option<Uuid>,
    pub device_id: Option<Uuid>,
    pub sale_number: String,
    pub subtotal: BigDecimal,
    pub tax_total: BigDecimal,
    pub discount_total: BigDecimal,
    pub grand_total: BigDecimal,
    pub payment_status: Option<String>,
    pub offline_created_at: DateTime<Utc>,
    pub items: Vec<CreateSaleItemRequest>,
    pub payments: Vec<CreateSalePaymentRequest>,
}

#[derive(Debug, Serialize)]
pub struct SaleResponse {
    pub id: Uuid,
    pub client_sale_id: Uuid,
    pub sale_number: String,
    pub grand_total: BigDecimal,
    pub payment_status: String,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, sqlx::FromRow)]
struct ExistingSaleRow {
    pub id: Uuid,
    pub sale_number: String,
    pub grand_total: BigDecimal,
    pub payment_status: String,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, sqlx::FromRow)]
struct CreatedSaleRow {
    pub id: Uuid,
    pub client_sale_id: Uuid,
    pub sale_number: String,
    pub grand_total: BigDecimal,
    pub payment_status: String,
    pub created_at: DateTime<Utc>,
}

pub async fn create_sale(
    maybe_auth: MaybeAuthUser,
    State(state): State<AppState>,
    Json(payload): Json<CreateSaleRequest>,
) -> AppResult<Json<SaleResponse>> {
    let mut tx = state.pool().await.begin().await?;

    // Determine organization_id and cashier_user_id (with fallback for terminal offline sessions)
    let (org_id, user_id) = if let Some(auth) = maybe_auth.0 {
        (auth.organization_id, auth.user_id)
    } else {
        let org_id = sqlx::query_scalar::<_, Uuid>(
            "SELECT organization_id FROM branches WHERE id = $1",
        )
        .bind(payload.branch_id)
        .fetch_optional(&mut *tx)
        .await?
        .unwrap_or_else(|| {
            Uuid::parse_str("67fe86f9-3f43-4db3-9d2d-aaa5fafcf3ad").unwrap()
        });

        let user_id = sqlx::query_scalar::<_, Uuid>(
            "SELECT id FROM users WHERE organization_id = $1 ORDER BY created_at ASC LIMIT 1",
        )
        .bind(org_id)
        .fetch_optional(&mut *tx)
        .await?
        .unwrap_or_else(Uuid::new_v4);

        (org_id, user_id)
    };

    // 1. Check idempotency using client_sale_id
    let existing_sale = sqlx::query_as::<_, ExistingSaleRow>(
        "SELECT id, sale_number, grand_total, payment_status, created_at FROM sales WHERE organization_id = $1 AND client_sale_id = $2",
    )
    .bind(org_id)
    .bind(payload.client_sale_id)
    .fetch_optional(&mut *tx)
    .await?;

    if let Some(existing) = existing_sale {
        tx.rollback().await?;
        return Ok(Json(SaleResponse {
            id: existing.id,
            client_sale_id: payload.client_sale_id,
            sale_number: existing.sale_number,
            grand_total: existing.grand_total,
            payment_status: existing.payment_status,
            created_at: existing.created_at,
        }));
    }

    let payment_status = payload.payment_status.unwrap_or_else(|| "PAID".to_string());

    // 2. Insert Sale master record
    let sale = sqlx::query_as::<_, CreatedSaleRow>(
        r#"
        INSERT INTO sales (
            client_sale_id, organization_id, branch_id, pos_terminal_id,
            cashier_user_id, sale_number, subtotal, tax_total, discount_total,
            grand_total, payment_status, sale_type, offline_created_at, created_at
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 'RETAIL', $12, NOW())
        RETURNING id, client_sale_id, sale_number, grand_total, payment_status, created_at
        "#,
    )
    .bind(payload.client_sale_id)
    .bind(org_id)
    .bind(payload.branch_id)
    .bind(payload.pos_terminal_id)
    .bind(user_id)
    .bind(payload.sale_number)
    .bind(payload.subtotal)
    .bind(payload.tax_total)
    .bind(payload.discount_total)
    .bind(payload.grand_total)
    .bind(payment_status)
    .bind(payload.offline_created_at)
    .fetch_one(&mut *tx)
    .await?;

    // 3. Insert Line Items and atomically update Stock
    for item in payload.items {
        let tax_rate = item.tax_rate.unwrap_or_else(|| BigDecimal::from(0));
        let tax_amount = item.tax_amount.unwrap_or_else(|| BigDecimal::from(0));
        let discount_amount = item.discount_amount.unwrap_or_else(|| BigDecimal::from(0));

        sqlx::query(
            r#"
            INSERT INTO sale_items (
                sale_id, product_id, product_name, sku, quantity, unit_price,
                tax_rate, tax_amount, discount_amount, total_amount
            )
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
            "#,
        )
        .bind(sale.id)
        .bind(item.product_id)
        .bind(item.product_name)
        .bind(item.sku)
        .bind(&item.quantity)
        .bind(&item.unit_price)
        .bind(tax_rate)
        .bind(tax_amount)
        .bind(discount_amount)
        .bind(item.total_amount)
        .execute(&mut *tx)
        .await?;

        // Reduce stock in stock_balances with correct unique constraint (branch_id, product_id, location_area)
        let neg_qty = -&item.quantity;
        let new_balance = sqlx::query_scalar::<_, BigDecimal>(
            r#"
            INSERT INTO stock_balances (organization_id, branch_id, product_id, location_area, quantity, reserved_quantity, updated_at)
            VALUES ($1, $2, $3, 'SHOP_FLOOR', $4, 0, NOW())
            ON CONFLICT (branch_id, product_id, location_area)
            DO UPDATE SET
                quantity = stock_balances.quantity + EXCLUDED.quantity,
                updated_at = NOW()
            RETURNING quantity
            "#,
        )
        .bind(org_id)
        .bind(payload.branch_id)
        .bind(item.product_id)
        .bind(&neg_qty)
        .fetch_one(&mut *tx)
        .await?;

        // Record stock movement audit row with required location_area and balance_after
        sqlx::query(
            r#"
            INSERT INTO stock_movements (
                organization_id, branch_id, product_id, location_area, movement_type, quantity,
                balance_after, unit_cost, reference_type, reference_id, device_id, notes
            )
            VALUES ($1, $2, $3, 'SHOP_FLOOR', 'SALE', $4, $5, $6, 'SALE', $7, $8, 'POS Sale checkout')
            "#,
        )
        .bind(org_id)
        .bind(payload.branch_id)
        .bind(item.product_id)
        .bind(&neg_qty)
        .bind(new_balance)
        .bind(&item.unit_price)
        .bind(sale.id)
        .bind(payload.device_id)
        .execute(&mut *tx)
        .await?;
    }

    // 4. Insert Payments
    for pmt in payload.payments {
        let currency = pmt.currency.unwrap_or_else(|| "KES".to_string());
        let change_given = pmt.change_given.unwrap_or_else(|| BigDecimal::from(0));

        sqlx::query(
            r#"
            INSERT INTO sale_payments (sale_id, payment_method, amount, currency, reference, change_given)
            VALUES ($1, $2, $3, $4, $5, $6)
            "#,
        )
        .bind(sale.id)
        .bind(pmt.payment_method)
        .bind(pmt.amount)
        .bind(currency)
        .bind(pmt.reference)
        .bind(change_given)
        .execute(&mut *tx)
        .await?;
    }

    tx.commit().await?;

    Ok(Json(SaleResponse {
        id: sale.id,
        client_sale_id: sale.client_sale_id,
        sale_number: sale.sale_number,
        grand_total: sale.grand_total,
        payment_status: sale.payment_status,
        created_at: sale.created_at,
    }))
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
pub struct SalesQuery {
    pub branch_id: Option<Uuid>,
    pub limit: Option<i64>,
    pub search: Option<String>,
}

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct SaleSummaryRow {
    pub id: Uuid,
    pub client_sale_id: Option<Uuid>,
    pub sale_number: String,
    pub branch_id: Uuid,
    pub branch_name: Option<String>,
    pub cashier_name: Option<String>,
    pub subtotal: BigDecimal,
    pub tax_total: BigDecimal,
    pub discount_total: BigDecimal,
    pub grand_total: BigDecimal,
    pub payment_status: String,
    pub payment_method: Option<String>,
    pub item_count: Option<i64>,
    pub created_at: DateTime<Utc>,
}

pub async fn list_sales(
    Query(params): Query<SalesQuery>,
    State(state): State<AppState>,
) -> AppResult<Json<Vec<SaleSummaryRow>>> {
    let pool = state.pool().await;
    let limit = params.limit.unwrap_or(100).min(500);

    let sales = if let Some(bid) = params.branch_id {
        sqlx::query_as::<_, SaleSummaryRow>(
            r#"
            SELECT 
                s.id, s.client_sale_id, s.sale_number, s.branch_id,
                b.name AS branch_name,
                u.name AS cashier_name,
                s.subtotal, s.tax_total, s.discount_total, s.grand_total,
                s.payment_status,
                (SELECT payment_method FROM sale_payments WHERE sale_id = s.id LIMIT 1) AS payment_method,
                (SELECT COUNT(*) FROM sale_items WHERE sale_id = s.id) AS item_count,
                s.created_at
            FROM sales s
            LEFT JOIN branches b ON s.branch_id = b.id
            LEFT JOIN users u ON s.cashier_user_id = u.id
            WHERE s.branch_id = $1
            ORDER BY s.created_at DESC
            LIMIT $2
            "#
        )
        .bind(bid)
        .bind(limit)
        .fetch_all(&pool)
        .await?
    } else {
        sqlx::query_as::<_, SaleSummaryRow>(
            r#"
            SELECT 
                s.id, s.client_sale_id, s.sale_number, s.branch_id,
                b.name AS branch_name,
                u.name AS cashier_name,
                s.subtotal, s.tax_total, s.discount_total, s.grand_total,
                s.payment_status,
                (SELECT payment_method FROM sale_payments WHERE sale_id = s.id LIMIT 1) AS payment_method,
                (SELECT COUNT(*) FROM sale_items WHERE sale_id = s.id) AS item_count,
                s.created_at
            FROM sales s
            LEFT JOIN branches b ON s.branch_id = b.id
            LEFT JOIN users u ON s.cashier_user_id = u.id
            ORDER BY s.created_at DESC
            LIMIT $1
            "#
        )
        .bind(limit)
        .fetch_all(&pool)
        .await?
    };

    Ok(Json(sales))
}

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct SaleItemRow {
    pub id: Uuid,
    pub product_id: Uuid,
    pub product_name: String,
    pub sku: String,
    pub quantity: BigDecimal,
    pub unit_price: BigDecimal,
    pub tax_rate: BigDecimal,
    pub tax_amount: BigDecimal,
    pub discount_amount: BigDecimal,
    pub total_amount: BigDecimal,
}

#[derive(Debug, Serialize, sqlx::FromRow)]
pub struct SalePaymentRow {
    pub id: Uuid,
    pub payment_method: String,
    pub amount: BigDecimal,
    pub currency: String,
    pub reference: Option<String>,
    pub change_given: BigDecimal,
}

pub async fn get_sale_details(
    Path(id): Path<Uuid>,
    State(state): State<AppState>,
) -> AppResult<Json<serde_json::Value>> {
    let pool = state.pool().await;

    let sale = sqlx::query_as::<_, SaleSummaryRow>(
        r#"
        SELECT 
            s.id, s.client_sale_id, s.sale_number, s.branch_id,
            b.name AS branch_name,
            u.name AS cashier_name,
            s.subtotal, s.tax_total, s.discount_total, s.grand_total,
            s.payment_status,
            (SELECT payment_method FROM sale_payments WHERE sale_id = s.id LIMIT 1) AS payment_method,
            (SELECT COUNT(*) FROM sale_items WHERE sale_id = s.id) AS item_count,
            s.created_at
        FROM sales s
        LEFT JOIN branches b ON s.branch_id = b.id
        LEFT JOIN users u ON s.cashier_user_id = u.id
        WHERE s.id = $1
        "#
    )
    .bind(id)
    .fetch_optional(&pool)
    .await?;

    let sale = match sale {
        Some(s) => s,
        None => return Err(AppError::NotFound("Sale not found".into())),
    };

    let items = sqlx::query_as::<_, SaleItemRow>(
        r#"
        SELECT id, product_id, product_name, sku, quantity, unit_price,
               tax_rate, tax_amount, discount_amount, total_amount
        FROM sale_items
        WHERE sale_id = $1
        "#
    )
    .bind(id)
    .fetch_all(&pool)
    .await?;

    let payments = sqlx::query_as::<_, SalePaymentRow>(
        r#"
        SELECT id, payment_method, amount, currency, reference, change_given
        FROM sale_payments
        WHERE sale_id = $1
        "#
    )
    .bind(id)
    .fetch_all(&pool)
    .await?;

    Ok(Json(serde_json::json!({
        "sale": sale,
        "items": items,
        "payments": payments
    })))
}

pub fn router() -> Router<AppState> {
    Router::new()
        .route("/sales", get(list_sales).post(create_sale))
        .route("/sales/:id", get(get_sale_details))
}
